# Generated by Django 3.2.6 on 2021-09-01 01:50

from django.db import migrations

def create_default_rewards(apps, schema_editor):
    # Default rewards
    REWARDS_DEFAULT = [
        {'name': 'spider', 'text': 'Spider Avatar', 'price': 0},
        {'name': 'food', 'text': 'Food (10 HP)', 'price': 75},
        {'name': 'potion', 'text': 'Potion (40 HP)', 'price': 275},
        {'name': 'orc', 'text': 'Orc Avatar', 'price': 500},
        {'name': 'elf', 'text': 'Elf Avatar', 'price': 950},
        {'name': 'villager', 'text': 'Villager Avatar', 'price': 1500},
        {'name': 'knight', 'text': 'Knight Avatar', 'price': 2600},
        {'name': 'witch', 'text': 'Witch Avatar', 'price': 2800},
        {'name': 'reaper', 'text': 'Reaper Avatar', 'price': 3500}
    ]
    # Get the 'Reward' model:
    Reward = apps.get_model('main_app', 'Reward')
    for item in REWARDS_DEFAULT:
        # If the reward already exist, skip:
        if Reward.objects.filter(name=item['name']):
            continue
        # If the reward does not exist, create it:
        Reward.objects.create(
            name=item['name'],
            text=item['text'],
            price=item['price']
        )


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_rewards)
    ]
