# Generated by Django 3.2.6 on 2021-09-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_create_rewards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
