# Generated by Django 3.2.6 on 2021-09-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_reward_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rewards_owned',
            field=models.ManyToManyField(to='main_app.Reward'),
        ),
    ]
