# Generated by Django 3.2.6 on 2021-09-02 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_user_rewards_owned'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hp_last_decreased',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 9, 2, 21, 25, 39, 21303)),
            preserve_default=False,
        ),
    ]
