# Generated by Django 3.2.6 on 2021-08-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gold',
            field=models.IntegerField(default=100),
        ),
    ]
