# Generated by Django 3.2.6 on 2021-09-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210904_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='habits',
            field=models.ManyToManyField(to='main_app.Habit'),
        ),
    ]
