# Generated by Django 3.2.6 on 2021-09-04 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_user_habits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='last_checked',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
