# Generated by Django 3.2.6 on 2021-09-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_habit_last_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='description',
            field=models.CharField(default='', max_length=150),
        ),
    ]
