# Generated by Django 3.2.6 on 2021-09-12 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_daily_last_completed_prev'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='last_reset',
            new_name='last_marked',
        ),
        migrations.AddField(
            model_name='user',
            name='last_deduct',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
